### ISSUE TITLE
Filename of LMIC_node.h mixed case

### ISSUE THREAD

**Issue by ernstdevreede** [lnlp/LMIC-node#1]
In LMIC_node.cpp the file is included by #include "lmic_node.h", but it is actually named LMIC_node.h.
Might work on systems insensitive to file name case, but not on Linux.I had to change the line to #include "LMIC_node.h"

**Comment by lnlp** [comment]
Good catch!

I missed it because I'm using Windows which has a case insensitive file system.

B.t.w. LMIC-node.cpp and LMIC-node.h have hyphens in their name (not underscores),
the Board Support Files use underscores to match the board-id's.

The issue has been fixed.

Thanks for your feedback!
