### ISSUE TITLE
MIC mismatch with ttgo lora

### ISSUE THREAD

**Issue by Bighoneypot** [lnlp/LMIC-node#20]
Hi, with this firmware I have always error in TTN:
Join-request to cluster-local join server failed MIC mismatch

Do you have a idea?

Can you hel me? Thank you!

on terminal:

Device-id:     ttgo-lora32-v1
LMIC library:  MCCI
Activation:    OTAA
Interval:      60 seconds    

000000023153:  Event: EV_JOINING

000000023943:  doWork job started
000000161248:  Event: EV_TXSTART
000000555186:  Event: EV_JOIN_TXCOMPLETE

**Comment by lnlp** [comment]
@Bighoneypot
Please respond.
Did above help to solve your issue?

**Comment by Bighoneypot** [comment]
@lnlp 
Gday,
yes I solve my issue with remove entire application and after I create new application the device work fine.

**Comment by lnlp** [comment]
Thanks. Good to hear your issue has been solved.
