### ISSUE TITLE
How to add MAC commands to uplinks?

### ISSUE THREAD

**Issue by BNNorman** [lnlp/LMIC-node#25]
I want to use the linkCheckReq MAC command. The server should report the gateway margin and number of gateways which picked up the signal.

This could be very useful when installing nodes to ensure there is gateway redundancy (more reliability). The gateway margin indicates the chances of being able to decode the received signal - if my reading/interpretation of the LoRaWAN spec is correct.

I know I have to expose gwmargin and ngws from lmic.h and lmic.c but I tried calling put_mac_uplink_byte(0x02); (after exposing the method) but didn't see any evidence in the V3 console that the MAC command was received, just the normal uplink messages on Port 10.

Can anyone help? I have posted a similar question on github for the MCCI library and asked for an enhancement to the library but no-one has commented in 5 days. (https://github.com/mcci-catena/arduino-lmic/issues/823)

**Comment by lnlp** [comment]
Hi @BNNorman,

I'm sorry but this is not an LMIC-node related issue but MCCI LMIC related. I will therefore close the issue.

I see that you created a feature request in the MCCI LMIC repository. Posting it as a question may help you get a quicker response quicker. Other options are to try the repository's Discussions or post a question on the MCCI forum.

As far as I'm aware the user of (MCCI) LMIC is more or less isolated from MAC commands.
It is possible to manually decode MAC command requests/responses from the data buffer of downlinks but I have no experience with this. Whether it is possible to send your own MAC commands via uplinks with LMIC I don't know.
