### ISSUE TITLE
What are opmodes? Are they listed somewhere?

### ISSUE THREAD

**Issue by tipo1000A** [lnlp/LMIC-node#29]
As the title says LMIC-node prints opmodes like:
opmode=0x4
opmode=0x808
opmode=0x900
opmode=0x908
. . ,
What they mean?

Thanks,
Tipo

**Comment by lnlp** [comment]
That is functionality of the LMIC library.

You can find definition of the opmodes with a brief description in [lmic.h](https://github.com/mcci-catena/arduino-lmic/blob/8d378ea410887d3fb08ea2c9acce95cc4c047788/src/lmic/lmic.h#L256).

**Comment by tipo1000A** [comment]
I can find opmodes 0x4 and 0x808 in lmic.h.

However, opmodes 0x900 and 0x908 are not in that list. How should I understand those modes?

**Comment by lnlp** [comment]
> opmodes 0x900 and 0x908 are not in that list. How should I understand those modes?

> Opmodes are MAC operation modes. They are functionality of the LMIC library.

The best place for asking that question is the [MCCI LMIC library repository](https://github.com/mcci-catena/arduino-lmic).
