### ISSUE TITLE
Sub-band selection

### ISSUE THREAD

**Issue by Alviunta** [lnlp/LMIC-node#34]
Hello.
This is a great example of how to develop a node with LoraWAN technology. Unlike what has been done here, I am using a private server ([Chirpstack](https://www.chirpstack.io/)) whose network is configured in the AU915 region, sub-band 0. How can I choose which sub-band I should use?
From what I understand TTN always works on the [same sub-band](https://www.thethingsnetwork.org/docs/lorawan/frequency-plans/#au915-928) and maybe this feature is hardcoded, if you can tell me how to change the setting I would appreciate it.

Greetings and congratulations for the great work done here.

**Comment by lnlp** [comment]
Hi, thanks. 

> How can I choose which sub-band I should use?

What about searching the sourcecode for 'subband'? 😉

Check for LMIC_selectSubBand in LMIC-node.cpp.
