### ISSUE TITLE
 Sparkfun ESP32 WROOM with RFM95W support

### ISSUE THREAD

**Issue by mike6000** [lnlp/LMIC-node#42]
Is it possible to get this board running with LMIC-node? https://www.sparkfun.com/products/18074

**Comment by lnlp** [comment]
It [looks like that should be possible](https://learn.sparkfun.com/tutorials/sparkfun-lora-gateway-1-channel-hookup-guide/turning-a-gateway-into-a-device).

I'm not sure whether this board is (directly) supported in PlatformIO Espressif 32 platform (ESP32 Arduino Core).
If not you may select a basic ESP32 board like esp32dev or one of the other basic ESP32 boards already supported by LMIC-node.

You will have to edit an existing BSF in LMIC-node for that (or create a new BSF yourself).
Important settings to adjust for your board are the LMIC pinmappings and possibly the SPI pins (if these do not match the standard SPI pins defined in the Arduino BSP).

If you need to explicitly set custom SPI pins (other than defined in the board's Arduino BSP) then have a look at the [BSF for the Lopy4](https://github.com/lnlp/LMIC-node/blob/157754e8164999349c6e7e80bb027a8e310c8ddc/src/boards/bsf_lopy4.h) for an example.
