### ISSUE TITLE
Spreading Factor can't be set

### ISSUE THREAD

**Issue by neo7530** [lnlp/LMIC-node#44]
Hey, 

How can i change the default SF from 7 to 9? Have done that in LMIC-node.h const dr_t DefaultABPDataRate = DR_SF9; but it still does Transmission with SF7 all times. Have disabled ADR too, but nothing changes...

**Comment by lnlp** [comment]
This is related to how the MCCI LMIC works. Better ask your question there: https://github.com/mcci-catena/arduino-lmic or try [The Things Network forum](https://www.thethingsnetwork.org/forum/).
